apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: darsh8699/studentapp:app-v21
        ports:
        - name: tomcat
          containerPort: 8080
          protocol: TCP
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
