apiVersion: v1 
kind: Service 
metadata: 
  name: studentapp-svc
spec: 
  selector: 
    app: student-app 
  ports: 
  - name: http 
    targetPort: 8080 
    port: 80
  type: LoadBalancer 
