apiVersion: v1 
kind: Service 
metadata: 
  name: proxy-forward-svc
spec: 
  selector: 
    app: proxy-forward-studentapp
  ports: 
  - name: http 
    targetPort: 80 
    port: 80
  type: LoadBalancer
